### ISSUE TITLE
Add way to handle tags in YAML input

### ISSUE THREAD

**Issue by mgajda** [dhall-lang/dhall-haskell#1148]
Yaml allows tagging parts of the structure by type or any user tag:
```yaml
local:
  port: !!userServiceable 8888
  ttl: 90
  errors: log
server:
  errors: syslog
```
It would be nice to be able to read them together with YAML configuration.

More examples here: https://stackoverflow.com/questions/15233335/i-dont-understand-what-a-yaml-tag-is
