### ISSUE TITLE
dhall-json: provide flag -o, --output for writing to file

### ISSUE THREAD

**Issue by DrSensor** [dhall-lang/dhall-haskell#1303]
Not having flag `-o` or `--output` can cause problems, especially for a project that use docker-compose as their development workflow. For example:

Given this docker-compose.yml
```yml
version: "3"
services:
  dhall-json:
    image: dhallhaskell/dhall-json
    entrypoint: [dhall-to-json]
    command: [--file, syntaxes/Dhall.dhall, --pretty]
    volumes:
      - ./syntaxes:/syntaxes:ro
```
If I run this
```sh
docker-compose run --rm --user $(id --user) dhall-json > Dhall.tmLanguage.json
```
it works but when there is an error, that error will be redirected to `Dhall.tmLanguage.json` and not printed in stderr.
There is a mode to disable pseudo-tty allocation, but it doesn't solve the problem. For example:
```sh
docker-compose run --rm -T --user $(id --user) dhall-json > Dhall.tmLanguage.json
```
the error is shown in the terminal but when it's succeeded, the results are not written into `Dhall.tmLanguage.json`.

---
Also, since the official docker image `dhallhaskell/dhall-json` is a minimal image (don't provide shell), this docker-compose file will not works:

```yml
version: "3"
services:
  dhall-json:
    image: dhallhaskell/dhall-json
    command: [/bin/sh, -c, "dhall-to-json --file syntaxes/Dhall.dhall --pretty > dist/Dhall.tmLanguage.json"]
    volumes:
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro
```
```console
$ docker-compose run --rm --user $(id --user) dhall-json
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

> Though I still prefer the official docker image to be minimal

###### References
<sup>https://docs.docker.com/compose/reference/run/<sup>
