### ISSUE TITLE
dhall-to-yaml: enable conversion for `Map NonList|NonRecord Any`

### ISSUE THREAD

**Issue by DrSensor** [dhall-lang/dhall-haskell#1379]
I've just noticed that `dhall-to-yaml` doesn't transform `Map Natural Text` which I use to define [.sublime-syntax match patterns](https://www.sublimetext.com/docs/3/syntax.html#match_patterns) (by converting `List/indexed` into `Map`)
```yaml
block-comment:
  - captures:
    - mapKey: 1
      mapValue: punctuation.definition.comment.scl.scl
    match: (/\*)(?:\s*(?=\s|(\*/)))?
    push:
    - meta_scope: comment.block
    - pop: true
      captures:
      - mapKey: 0
        mapValue: punctuation.definition.comment.scl.scl
      match: \*/
```
Unlike JSON, key in YAML can be any type _except_ List and Record, which are:
- [x] `Text`
- [ ] `Natural`
- [ ] `Integer`
- [ ] `Double`
- [ ] `Bool`
- [ ] `Optional Type`, except List and Record
- [ ] Union Type, except List and Record

Also, some type that I think need to be converted too on `dhall-to-json`:
- [ ] `None Text`, --omitEmpty will delete record field
- [ ] `Some Text`
- [ ] Union (Text | Optional Text | NoType )
