### ISSUE TITLE
yaml strings are quoted unnecessarily

### ISSUE THREAD

**Issue by Benjmhart** [dhall-lang/dhall-haskell#1617]
While building the Bitbucket pipeline typing for dhall - strings were unnecessarily quoted in the resulting yaml file,  which BB does not allow. here is YAML generated:

```yaml
image: "node 10.15.3"
pipelines:
  default:
    - step:
        caches: []
        name: "hello world"
        script:
          - "echo hello"
```

each of the 3 quoted strings ought to be unquoted.

a user-level override would be a good solution here,  maybe an unquoted String type that i could annotate whether my string should be quoted or not when compiling to yaml?
