### ISSUE TITLE
Cannot parse record with "assert" word as a key

### ISSUE THREAD

**Issue by srghma** [dhall-lang/dhall-haskell#2077]
with

```
{ assert = {} }
```

```
/home/srghma/projects/spago/.stack-work/install/x86_64-linux-nix/06cd1e2baf088e968f44629cc5d0f82d60e8d19f60357d1f3d3fedc9a57dd8c8/8.8.4/bin/spago build --watch
spago:
↳ ./spago.dhall
  ↳ ./packages.dhall
    ↳ ./upstream.dhall

Error: Invalid input

/home/srghma/projects/purescript-spec-should-equal-deep/upstream.dhall:1:3:
  |
1 | { assert = {} }
  |   ^
unexpected 'a'
expecting ',', =, whitespace, or }


1│                ./upstream.dhall

/home/srghma/projects/purescript-spec-should-equal-deep/packages.dhall:1:16
```

___________

with

```
{ sassert = {} }
```

no error

the dhall version used is (from commit cfce22f in https://github.com/purescript/spago/pull/695)

```
- completed:
    hackage: dhall-1.35.0@sha256:be822e7f49f0e7e77483c2c2fc5cea38db079dbbdf9cbf79d6621f5809accf49,34091
    pantry-tree:
      size: 301264
      sha256: ec5084129a8da542eae5b45b2febe193665b31b20086d8635dbe4dfc5c7c5516
  original:
    hackage: dhall-1.35.0
```
