### ISSUE TITLE
Produce unquoted YAML from Dhall

### ISSUE THREAD

**Issue by vmchale** [dhall-lang/dhall-haskell#2497]
Hello,

I'm trying to produce templated YAML from Dhall; the desired output is

```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

Basically I would want the output string to be unquoted so that the templating engine can pick up `"/configmap.yaml"`

(I came from a question [here](https://stackoverflow.com/questions/62106628/dhall-to-yaml-funtion-text-output-is-being-output-in-double-quotes), as far as I can tell there isn't a canonical solution!)

Thanks!
