### ISSUE TITLE
"Dynamic records" / --maps support in dhall-toml

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [dhall-lang/dhall-haskell#2509]
I'm new, so maybe this is the wrong way to go about the problem; but I'd like to generate a config like the following ([for `rtx`'s `~/.config/rtx/config.toml`](https://github.com/jdxcode/rtx#configuration)) in a relatively D.R.Y. / deduped way:

```toml
[plugins]
cabal = 'https://github.com/sestrella/asdf-ghcup.git'
ghc = 'https://github.com/sestrella/asdf-ghcup.git'
hls = 'https://github.com/sestrella/asdf-ghcup.git'
stack = 'https://github.com/sestrella/asdf-ghcup.git'

[tools]
cabal = "latest"
dotnet = "latest"
golang = "latest"
hls = "latest"
jq = "latest"
lua = "latest"
nodejs = "latest"
opam = "latest"
php = "latest"
purescript = "latest"
python = "latest"
racket = "latest"
ruby = "latest"
rust = "latest"
```

Reading the docs, it _feels_ like this needs ["Dynamic records"](https://docs.dhall-lang.org/tutorials/Getting-started_Generate-JSON-or-YAML.html#dynamic-records) support (or dependent typing 😅); but that doesn't seem to be supported by `dhall-toml` as yet:

```console
$ dhall-to-toml --file Dotfiles/config/rtx/config.dhall
[[plugins]]
  mapKey = "cabal"
  mapValue = "https://github.com/sestrella/asdf-ghcup.git"

[[plugins]]
  mapKey = "ghc"
  mapValue = "https://github.com/sestrella/asdf-ghcup.git"

[[plugins]]
  mapKey = "hls"
  mapValue = "https://github.com/sestrella/asdf-ghcup.git"

[[plugins]]
  mapKey = "stack"
  mapValue = "https://github.com/sestrella/asdf-ghcup.git"
```
