### ISSUE TITLE
list of unions not converted to maps

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-haskell#699]
I'm writing some GoCD pipeline configs in dhall and ran into the following issue. Given this dhall file:

```
let MaterialSource =
  { mapKey : Text
  , mapValue :
    { git : Text
    , branch : Text
    }
  }
in let MaterialPipeline =
  { mapKey : Text
  , mapValue :
    { pipeline : Text
    , stage : Text
    }
  }
in let Material = < Source : MaterialSource | Pipeline : MaterialPipeline >
in let unionMaterial = constructors Material
in let Materials = List Material
in let materials : Materials =
  [ unionMaterial.Source
    { mapKey = "someRepo"
    , mapValue =
      { git = "www.example.com/user/repo.git"
      , branch = "master"
      }
    }
  , unionMaterial.Pipeline
    { mapKey = "somePipeline"
    , mapValue =
      { pipeline = "someOtherPipeline"
      , stage = "build"
      }
    }
  ]
in materials
```

I get this output:

```
- mapKey: someRepo
  mapValue:
    branch: master
    git: www.example.com/user/repo.git
- mapKey: somePipeline
  mapValue:
    stage: build
    pipeline: someOtherPipeline
```

whereas I would have expected:

```
someRepo:
    branch: master
    git: www.example.com/user/repo.git
somePipeline:
    stage: build
    pipeline: someOtherPipeline
```

I originally opened this issue here https://github.com/dhall-lang/dhall-json/issues/71, and as @f-f pointed out there "this is currently not supported. In fact, it looks like [the homogeneous records conversion is applied specifically to lists](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall-json/src/Dhall/JSON.hs#L524), while [unions go through unconverted](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall-json/src/Dhall/JSON.hs#L637)."

Would be cool to add support for this if it's possible.

**Comment by Gabriel439** [comment]
Would it be possible to inside nest the union inside of the `mapValue` field, like this?

```haskell
let MaterialSource = { git : Text, branch : Text }

let MaterialPipeline = { pipeline : Text, stage : Text }

let Material = < Source : MaterialSource | Pipeline : MaterialPipeline >

let Materials = List { mapKey : Text, mapValue : Material }

let materials
    : Materials
    = [ { mapKey =
            "someRepo"
        , mapValue =
            Material.Source
            { git = "www.example.com/user/repo.git", branch = "master" }
        }
      , { mapKey =
            "somePipeline"
        , mapValue =
            Material.Pipeline
            { pipeline = "someOtherPipeline", stage = "build" }
        }
      ]

in  materials
```

Note: The above example uses the latest version of Dhall, which supports multi-`let` and removes the need for `constructors`

This produces the desired result:

```yaml
someRepo:
  branch: master
  git: www.example.com/user/repo.git
somePipeline:
  stage: build
  pipeline: someOtherPipeline
```

The first reason I suggest refactoring things in this way is because I tried to implement what you suggested and ran into the issue where it would misbehave when the association list is empty.  The current code uses the type of the list to know when it still needs to convert an empty association list to an empty homogeneous map, but once you strip the constructors from the list elements then the list elements no longer have a valid shared type.  Without the shared element type the conversion misbehaves on empty lists.

The second reason I suggest doing things in this way is because it will provide a smoother migration path when support for `toMap` is standardized (See: https://github.com/dhall-lang/dhall-lang/issues/234).  Once `toMap` is available then your example would simplify further to:

```haskell
let MaterialSource = { git : Text, branch : Text }

let MaterialPipeline = { pipeline : Text, stage : Text }

let Material = < Source : MaterialSource | Pipeline : MaterialPipeline >

let Materials = List { mapKey : Text, mapValue : Material }

let materials
    : Materials
    = toMap
      { someRepo =
          Material.Source
          { git = "www.example.com/user/repo.git", branch = "master" }
      , somePipeline =
          Material.Pipeline { pipeline = "someOtherPipeline", stage = "build" }
      }

in  materials
```

... and that simplification only works if you wrap each `mapValue` in a union instead of wrapping the `mapKey`/`mapValue` pair in a union.
